---
title: "Cleaning notes"
author: "Joao Martins"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=here::here('docs', 'cleaning.html')) })
output:
  html_document:
    toc: true
    theme: united
    highlight: breezedark
    toc_float: true
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R", "global.R"))
```

## Science Magazine
```{r, eval=FALSE}
science_issues <-
  readr::read_csv(here::here("data-raw", "sciencemag-issues.csv"))

# TODO: https://github.com/zambujo/editorials/issues/17
science_highlights <-
  readr::read_csv(here::here("data-raw", "sciencemag-highlights.csv")) %>%
  ## un-nest or "explode" multiple references
  dplyr::mutate(ref = stringr::str_split(ref, "(?<=[[:space:]][(][12][0-9]{3}[)][;])")) %>%
  tidyr::unnest(ref) %>%
  dplyr::mutate(
    ref = stringr::str_squish(ref),
    ref = stringr::str_remove(ref, "[;.]$"),
    doi = stringr::str_extract(ref, doi_regex),
    journal = "science",
    issue_key = stringr::str_remove(editorial_key, "/twil"),
    url_rel = stringr::str_remove(highlight_key, "[.]full[.]html"),
    url = stringr::str_c("https://science.sciencemag.org/content", url_rel)
  ) %>%
  ## add year of the editorial highlight
  dplyr::left_join(science_issues, by = "issue_key") %>%
  dplyr::select(
    journal,
    hl_year = issue_year,
    hl_topic = topic,
    hl_title = title,
    hl_url = url,
    citation = ref,
    resource = doi
  )

science_highlights %>%
  readr::write_csv(here::here("data-raw", "science_highlights_clean.csv"))
```

## Nature Journal
```{r, eval=FALSE}
nature_issues <-
  readr::read_csv(here::here("data-raw", "nature-issues.csv")) %>%
  dplyr::mutate(year = stringr::str_extract(issue_date, "\\d{4}"),
                year = as.numeric(year))

nature_contents <-
  readr::read_csv(here::here("data-raw", "nature-contents.csv"))

nature_highlights <-
  readr::read_csv(here::here("data-raw", "nature-highlights.csv")) %>%
  dplyr::mutate(
    journal = "nature",
    doi = stringr::str_remove(doi, "https[:]//doi.org/"),
    url = stringr::str_c("https://www.nature.com", article_key)
  ) %>%
  dplyr::left_join(nature_contents, by = "article_key") %>%
  dplyr::left_join(nature_issues, by = "issue_key") %>%
  dplyr::select(
    journal,
    hl_year = year,
    hl_topic = topic,
    hl_title = title,
    hl_url = url,
    citation,
    resource = doi
  )

nature_highlights %>%
  readr::write_csv(here::here("data-raw", "nature_highlights_clean.csv"))
```



## Combining and exporting
```{r, eval=FALSE}
source(here::here("R", "doi_utils.R"))
dplyr::bind_rows(
  readr::read_csv(here::here("data-raw", "science_highlights_clean.csv")),
  readr::read_csv(here::here("data-raw", "nature_highlights_clean.csv"))) %>%
  dplyr::arrange(hl_url) %>%
  # extract DOIs
  tidyr::extract(resource, "doi", sprintf("(%s)", doi_regex), remove=FALSE) %>%
  dplyr::mutate(doi = stringr::str_to_lower(doi)) %>%
  readr::write_csv(here::here("data", "research_highlights.csv"))

# TODO: https://github.com/zambujo/editorials/issues/16
df <- highlights %>%
  dplyr::mutate(
    citation = stringr::str_remove(citation, "doi[:][[:space:]]?"),
    cit_journal = stringr::str_extract(citation, "([A-Z][A-Za-z.[:space:]]+)+"),
    cit_issue = stringr::str_extract(citation, "[0-9]+[,][[:space:]][0-9–]+"),
    cit_year = stringr::str_extract(citation, "[(]\\d{4}[)]"),
    cit_journal = stringr::str_squish(cit_journal)
  )
```



## Resolve normal- and short-DOIs (TODO)
```{r, eval=FALSE}
source(here::here("R", "doi_utils.R"))
highlights <- readr::read_csv(here::here("data", "research_highlights.csv"))

dois <- highlights %>%
  filter(!is.na(doi)) %>%
  distinct(doi) %>%
  pull()

# TODO: save full_dois



# TODO: simplify below logic
short_dois <-
  highlights %>%
  dplyr::distinct(resource) %>%
  tidyr::drop_na() %>%
  dplyr::filter(stringr::str_detect(resource, "doi[.]org")) %>%
  dplyr::filter(!stringr::str_detect(resource, doi_regex)) %>%
  dplyr::mutate(
    resource = stringr::str_to_lower(resource),
    resource = stringr::str_trim(resource),
    resource = stringr::str_split(resource, "/"),
    resource = purrr::map(resource, tail, n = 1),
    resource = purrr::flatten_chr(resource)
  ) %>%
  dplyr::pull()

session_bow <- polite::bow(url = "http://doi.org",
                           user_agent = settings$agent)
purrr::walk(
  short_dois,
  resolve_shortdoi,
  polite_bow = session_bow,
  csv_path = here::here("data-raw", "short_dois.csv")
)
```


## Gather Crossref metadata (TODO)

```{r, eval=FALSE}
resolved_dois <-
  readr::read_csv(here::here("data-raw", "short_dois.csv"))
full_dois <- 
  readr::read_csv(here::here("data-raw", "full_dois.csv"))

# cr metadata for resolved shortDOIs --------------------------------------
# resolved_dois <- resolved_dois %>%
#   tidyr::drop_na() %>%
#   dplyr::mutate(
#     doi = stringr::str_remove(doi, "^doi:"),
#     doi = stringr::str_to_lower(doi),
#     doi = stringr::str_trim(doi)
#   )

# combine data and export -------------------------------------------------
dplyr::pull(resolved_dois, doi) %>%
  c(dplyr::pull(full_dois, doi)) %>%
  unique() # ..... TODO: get Crossref data
  # dplyr::distinct(doi, .keep_all = TRUE) %>%
  # dplyr::arrange(date) %>%
  # dplyr::mutate(
  #   cr_title = stringr::str_squish(cr_title),
  #   cr_year = stringr::str_sub(cr_year, 1, 4)) %>%
  # readr::write_csv(here::here("data", "crossref.csv"))

```

## Funding information

```{r, eval=FALSE}
source(here::here("R", "doi_utils.R"))
curated <-
  dplyr::bind_rows(
    readr::read_tsv(here::here(
      "data-raw",
      "Science_EdChoice_cleaned.txt"
    )) %>%
      dplyr::select(
        highlight_url,
        highlight_ref_doi),
    readr::read_tsv(
      here::here(
        "data-raw",
        "Nature_ResearchHighlights_cleaned.txt")
    ) %>%
      dplyr::select(
        highlight_url,
        highlight_ref_doi)
  )

dois <- curated %>%
  dplyr::mutate(highlight_ref_doi = stringr::str_squish(highlight_ref_doi)) %>%
  tidyr::extract(highlight_ref_doi, 
                 "doi", 
                 sprintf("(%s)", doi_regex), 
                 remove = TRUE) %>%
  dplyr::mutate(doi = stringr::str_to_lower(doi)) %>%
  dplyr::filter(!is.na(doi)) %>%
  dplyr::distinct(doi) %>%
  dplyr::pull()

session_bow <- polite::bow(url = "https://api.crossref.org",
                           user_agent = settings$agent)

cr_handle <- function(doi, polite_bow) {
  json <- get_cr_raw(doi, polite_bow)
  crossref_basic(doi, json, here::here("data-raw", "doi_meta.csv"))
  crossref_funders(doi, json, here::here("data-raw", "doi_fund.csv"))
}

dois %>% 
  purrr::walk(cr_handle, polite_bow = session_bow)
```
