---
title: "Scraping notes"
author: "Joao Martins"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=here::here('docs', 'scraping.html')) })
output:
  html_document:
    toc: true
    theme: united
    highlight: breezedark
    toc_float: true
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R", "global.R"))
```

## Sicence Magazine

```{r sciencemag, eval=FALSE}
source(here::here("R", "sciencemag.R"))
session_bow <- polite::bow(url = "https://science.sciencemag.org",
                           user_agent = settings$agent)
# issues ...
time_period %>%
  purrr::walk(
    get_sciencemag_issues,
    polite_bow = session_bow,
    csv_path = here::here("data-raw", "sciencemag-issues.csv")
  )

# articles ...
readr::read_csv(here::here("data-raw", "sciencemag-issues.csv")) %>%
  dplyr::mutate(archive_links = stringr::str_c(issue_key, "/twil")) %>%
  dplyr::pull(archive_links) %>%
  purrr::walk(
    get_sciencemag_articles,
    polite_bow = session_bow,
    csv_path = here::here("data-raw", "sciencemag-highlights.csv")
  )
```

## Nature Journal

```{r nature, eval=FALSE}
source(here::here("R", "nature.R"))
session_bow <- polite::bow(url = "https://www.nature.com",
                           user_agent = settings$agent)
# volumes ...
nature_volumes <- get_nature_volumes(polite_bow = session_bow) %>%
  dplyr::filter(year %in% time_period)
# issues ...
nature_volumes %>%
  dplyr::pull(volume_key) %>%
  purrr::map(
    get_nature_issues,
    polite_bow = session_bow,
    csv_path = here::here("data-raw", "nature-issues.csv")
  )

# contents ...
readr::read_csv(here::here("data-raw", "nature-issues.csv")) %>%
  dplyr::pull(issue_key) %>%
  purrr::walk(
    get_nature_contents,
    polite_bow = session_bow,
    csv_path = here::here("data-raw", "nature-contents.csv")
  )

# articles ...
readr::read_csv(here::here("data-raw", "nature-contents.csv")) %>%
  dplyr::filter(stringr::str_detect(contents_labels, "Research Highlight")) %>%
  dplyr::pull(article_key) %>%
  purrr::walk(
    get_nature_articles,
    polite_bow = session_bow,
    csv_path = here::here("data-raw", "nature-highlights.csv")
  )
```
